[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~0.8.0"

[[constraint]]
  name = "github.com/tealeg/xlsx"
  version = "~1.0.3"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "~2.2.6"

[[constraint]]
  branch = "master"
  name = "github.com/araddon/dateparse"
